### ISSUE TITLE
Title crashes during game play

### ISSUE THREAD

**Issue by blinky01001** [dreadnought-friends/support-tool#9]
Hello,

I wold like to report a crash that occurs during game play.

The issue occurs randomly once every 2 games.

Also I'm having problems getting the "msinfo" data from run, I've attached a picture showing the error
I've attached all longs from today in one zip "Blinky01001 - 28.06.2017 Logs" the latest one is from crash
Please note that this crash started to occur since the last update not the 1.7.1

![msinfo error](https://user-images.githubusercontent.com/29760190/27653244-33359926-5c47-11e7-9456-16448d6711d5.jpg)
 
[Blinky01001 - 28.06.2017 Logs.zip](https://github.com/dreadnought-friends/support-tool/files/1109765/Blinky01001.-.28.06.2017.Logs.zip)
[Blinky01001 - DxDiag.txt](https://github.com/dreadnought-friends/support-tool/files/1109766/Blinky01001.-.DxDiag.txt)

**Comment by linaori** [comment]
Heya!

Regarding the msinfo issue, this file should be available on your system as it comes with windows. Can you try the following things?
 1. Check this link and see if you can open msinfo this way https://www.howtogeek.com/196893/how-to-open-the-system-information-panel-on-windows-8/
 2. If this works, try running the tool again to see if it works
 3. If it still gives the same error, open the command prompt
 4. Try `where msinfo` (or `where msinfo32` if it doesn't work) and post it here 
 5. If this doesn't work, browse to `C:\program files\common files\microsoft shared\msinfo` and see if you can run msinfo from there. In theory, running it from here should should make it possible to run to tool again, but this is only my speculation.

Can you report back if you got it to work and if so, how? I can write an extra check in the tool based on which issue was causing the tool to not find msinfo on your system.

Sadly I can't really help with the bugs/crashes in-game. But judging by the error in your logs, it seems like windows DVR might be causing a problem. I personally had the same issue and after turning it off, my game stopped crashing. If this doesn't solve it, contact Customer Support: https://support.greybox.com/hc/en-us/requests/new

Turning off DVR: https://support.steampowered.com/kb_article.php?ref=6239-DZCB-8600#xboxapp

**Comment by blinky01001** [comment]
Hello,

Thank you so much for the replay, I've uploaded the "msinfo" 
Worked by using the msinfo32 in RUN

[Blinky01001 - msinfo.zip](https://github.com/dreadnought-friends/support-tool/files/1112961/Blinky01001.-.msinfo.zip)

Also please note that the DVR feature was off.

I will play the game and see if I crash again.

I have a dump from a previous crash that I created with  the task manager, if it helps please tell me how can I provide it to you guys. [3.70GB :(]

**Comment by linaori** [comment]
I'm not working for 6ft or yager, I'm just a player like you, so you'll have to to contact them through the official support channels for that crash. 

Now that `msinfo32` did work, does running the tool work again as well?

**Comment by linaori** [comment]
Closing the issue as you seem to be able to report the crash to CS now
